### ISSUE TITLE
'yarn package', random questions

### ISSUE THREAD

**Issue by JoeRoddy** [alexvcasillas/reactron#2]
Readme says to run `yarn run package`, but the package.json only has a 'pack' script, should the readme be changed?  The name of the script?

Have you gotten the chance to test the build process for all 3 platforms yet?  I can't quite seem to get the app to launch on linux (after packaging).

Let me know if I'm getting annoying. ;D

**Comment by JoeRoddy** [comment]
Terminal output  when running the app created by `yarn pack`: 
![joe joe-xps -desktop-reactron-dist-linux-unpacked_001](https://user-images.githubusercontent.com/16690442/36870111-f35789cc-1d6b-11e8-80e8-0c7091c49de1.png)

**Comment by alexvcasillas** [comment]
You're not getting annoying, no worries. It's nice to see issues from people, it's interesting for the project.

The `yarn run package`is a typo at the readme, should be `yarn run pack`.

I've managed to get the packed and running at Mac OSX : )

**Comment by JoeRoddy** [comment]
Okay, I have it working on Linux with `yarn run pack` as well as `yarn run dist` (the installer works perfectly, even shows up in my app tray without having to make desktop files).

From [this](https://github.com/electron-userland/electron-builder/issues/303), I changed package.json main prop from 
`"main": "main.js",`
to:
`"main": "./main.js",`

Not going to pretend like I know if this will affect Mac or Windows builds at all, so it's something that should probably be tested out a bit.

**Comment by alexvcasillas** [comment]
Nice to hear that you have it working : )

I'll keep the testings on Mac and Windows 👍
